<?xml version="1.0" encoding="utf-8"?><Database Name="db_quanlydienthoai" Class="ManagerPhoneDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=duongson-pc\sqlexpress;Initial Catalog=db_quanlydienthoai;Integrated Security=True" SettingsObjectName="QLSanPham.Properties.Settings" SettingsPropertyName="db_quanlydienthoaiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.product" Member="products">
    <Type Name="product">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="code_trademark" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="trademark_product" Member="trademark" ThisKey="code_trademark" OtherKey="code" Type="trademark" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.trademark" Member="trademarks">
    <Type Name="trademark">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="trademark_product" Member="products" ThisKey="code" OtherKey="code_trademark" Type="product" />
    </Type>
  </Table>
</Database>